#!/usr/bin/env node
'use strict';
var copyfiles = require('./index');
var args = require('yargs')

args.alias('u', 'up')
  .describe('u', 'slice a path off the bottom of the paths')
  .coerce('u', function (i) {
    return parseInt(i, 10);
  })
if (args.argv.$0.indexOf('up') > -1) {
  args.default('u', '1');
}
args.alias('a', 'all')
  .describe('a', 'include files and directories whose names begin with a dot (.)')
  .boolean('a')
  .alias('f','flat')
  .describe('f', 'flatten the output')
  .boolean('f')
  .alias('e', 'exclude')
  .describe('e', 'pattern or glob to exclude (may be passed multiple times)')
  .alias('s','soft')
  .boolean('s')
  .describe('s', 'do not overwrite destination files if they exist')
  .usage('$0 [options] inFile [more files ...] outDirectory').help()
  .alias('v', 'version')
  .alias('h', 'help')
var argv = args.argv;
if (argv.flat) {
  argv.up = true;
}
console.log('argv', argv)
copyfiles(argv._, argv, function (err) {
  if (err) {
    console.error(err);
    process.exit(1);
  } else {
    process.exit(0);
  }
});
